<a href="https://colab.research.google.com/github/namthuan2304/DM_2024/blob/main/Lab_1_21130556_DangNamThuan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DM Lab 1: Introduction to Python:
# 21130556 - Đặng Nam Thuận


---

# Import libraries

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/Colab Notebooks/DM_Labs'

Mounted at /content/gdrive
/content/gdrive/MyDrive/Colab Notebooks/DM_Labs

#Task 1. Introduction to Python

#1.1. Implement Python functions as follows:
1.   S(n)=1 - 2 + 3 - 4+ … + ((-1) ^ (n + 1)).n , 		n>0
2.   S(n)=1 ^ 2 + 2^2 + 3^2 + ... + n^2 , 			n>0

In [196]:
#1. S(n)=1 - 2 + 3 - 4+ … + ((-1) ^ (n + 1)).n , n>0
def S1():
    n = int(input("Enter a positive integer value for n: "))
    if n <= 0:
        print("n must be a positive integer.")
        return

    re = 0
    for i in range(1, n+1):
        re += ((-1) ** (i + 1)) * i
    print(f"S1({n}) = {re}")

#2. S(n)=1 ^ 2 + 2^2 + 3^2 + ... + n^2 , n>0
def S2():
    n = int(input("Enter a positive integer value for n: "))
    if n <= 0:
        print("n must be a positive integer.")
        return

    re = 0
    for i in range(1, n+1):
        re += i**2
    print(f"S2({n}) = {re}")

S1()
S2()

Enter a positive integer value for n: -9
n must be a positive integer.
Enter a positive integer value for n: 9
S2(9) = 285

#1.2. For a given class diagram (in Java) as follows:
![image.png]()

Implements the following methods:


1.   Count the number of employees having birthYear equals to a given year
2.   Find the employee with highest age
3.   Summary employees by birth years. Report results as a dictionary structure.

In [46]:
from datetime import datetime
class Employee:
      def __init__(self, id, name, birthYear, salaryRate):
        self.__id = id
        self.__name = name
        self.__birthYear = birthYear
        self.__salaryRate = salaryRate

      def get_birthYear(self):
        return self.__birthYear

      def get_ages(self):
        current_year = datetime.now().year
        return current_year - self.__birthYear

      def __repr__(self):
        return self.__name

In [59]:
class Department:
      def __init__(self, name):
        self.__name = name
        self.__employees = list()

      def set_employees(self, employees):
        if employees:
            self.__employees.extend(employees)

      #1. Count the number of employees having birthYear equals to a given year
      def countBirthYearEqual(self, year):
        if not self.__employees:
          return None
        re = 0
        for employee in self.__employees:
          if employee.get_birthYear() == year:
            re += 1
        return re

      #2. Find the employee with highest age
      def findHighestAge(self):
        if not self.__employees:
          return None
        max_age = -1
        employees_max_age = None
        for employee in self.__employees:
          if employee.get_ages() > max_age:
            max_age = employee.get_ages()
            employees_max_age = employee

        return employees_max_age

      #3. Summary employees by birth years. Report results as a dictionary structure.
      def filterByBirthYear(self):
        if not self.__employees:
          return None
        s = set()
        re = dict()
        for employee in self.__employees:
          s.add(employee.get_birthYear())
        for year in s:
          re[year] = self.countBirthYearEqual(year)
        return re

In [61]:
e1 = Employee(1, "John", 1994, 5.5)
e2 = Employee(2, "Tom", 1996, 5.6)
e3 = Employee(3, "Iris", 1992, 5.8)
e4 = Employee(4, "Elva", 1992, 5.9)
e5 = Employee(5, "Duke", 1995, 6.3)

l = list()
l.append(e1)
l.append(e2)
l.append(e3)
l.append(e4)
l.append(e5)

department = Department("Noi vu")
department.set_employees(l)

print(department.countBirthYearEqual(1992))
print(department.findHighestAge())
department.filterByBirthYear()

2
Iris

{1992: 2, 1994: 1, 1995: 1, 1996: 1}

#Task 2. NumPy

#2.1. Generate a numpy array with 100 integer values from 1 to 20  without using any loop.

In [79]:
array = np.random.randint(1, 21, size=100)
array

array([ 4,  6, 10, 18,  6, 13,  2, 17,  6, 15, 20,  7, 12, 14,  4, 16, 20,
       17,  1, 10, 20, 19,  2, 17, 16,  4,  3, 11, 12, 14,  4, 14,  3, 14,
       12, 18, 13,  7, 11, 10, 13,  5,  5,  2, 19, 13, 17,  1, 16,  1,  3,
       18, 19, 17,  9,  6,  4, 17, 12, 20, 17, 19, 19,  7,  3,  6, 10,  5,
        1, 18, 16,  4, 13, 10, 13, 15,  3,  2, 10, 17,  3, 17, 18, 15, 10,
       19,  9, 10,  5, 15,  8,  4,  7,  2,  7,  6, 13, 17, 16,  5])

#2.2. Replace all elements of the array generated in 2.1. that are greater than a specified value (***v***) by ***v***

In [80]:
v = int(input("Enter v: "))
array[array > v] = v
array

Enter v: 8

array([4, 6, 8, 8, 6, 8, 2, 8, 6, 8, 8, 7, 8, 8, 4, 8, 8, 8, 1, 8, 8, 8,
       2, 8, 8, 4, 3, 8, 8, 8, 4, 8, 3, 8, 8, 8, 8, 7, 8, 8, 8, 5, 5, 2,
       8, 8, 8, 1, 8, 1, 3, 8, 8, 8, 8, 6, 4, 8, 8, 8, 8, 8, 8, 7, 3, 6,
       8, 5, 1, 8, 8, 4, 8, 8, 8, 8, 3, 2, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8,
       5, 8, 8, 4, 7, 2, 7, 6, 8, 8, 8, 5])

#2.3. Find the most frequent value in the array obtained from Task 2.2

In [82]:
unique, counts = np.unique(array, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]
most_frequent_value

8

#Task 3. Pandas

In [170]:
dataset = pd.read_csv('countries.csv')
dataset

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987
1,Albania,Europe,2877800.0,78.57,2.89,11803.431
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839
3,Andorra,Europe,77265.0,83.73,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495
...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775

#3.1 List all **continents** in the dataset

In [189]:
df = pd.DataFrame(data=dataset)
df['continent']

0        Asia
1      Europe
2      Africa
3      Europe
4      Africa
        ...
205      Asia
206    Africa
207      Asia
208    Africa
209    Africa
Name: continent, Length: 210, dtype: object

# 3.2. Get 10 countries that have highest **life_expectancy** as a dataframe.

In [172]:
df1 = df.sort_values(by='life_expectancy', ascending=False).head(10)
df1

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
127,Monaco,Europe,39244.0,86.75,13.80,NaN
162,San Marino,Europe,33938.0,84.97,3.80,56861.470
87,Hong Kong,Asia,7496988.0,84.86,NaN,56054.920
99,Japan,Asia,126476458.0,84.63,13.05,39002.223
37,Cayman Islands,North America,65720.0,83.92,NaN,49903.029
183,Switzerland,Europe,8654618.0,83.78,4.53,57410.166
3,Andorra,Europe,77265.0,83.73,NaN,NaN
169,Singapore,Asia,5850343.0,83.62,2.40,85535.383
177,Spain,Europe,46754783.0,83.56,2.97,34272.360
97,Italy,Europe,60461828.0,83.51,3.18,35220.084

#3.3. Get 10 countries with the highest **GDP per capita**, among the countries with **population** greater than 100 million as a dataframe

In [173]:
df2 = df.sort_values(by='gdp_per_capita', ascending=False).head(10)
df2

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
155,Qatar,Asia,2881060.0,80.23,1.20,116935.600
115,Luxembourg,Europe,625976.0,82.25,4.51,94277.965
169,Singapore,Asia,5850343.0,83.62,2.40,85535.383
29,Brunei,Asia,437483.0,75.86,2.70,71809.251
94,Ireland,Europe,4937796.0,82.30,2.96,67335.293
197,United Arab Emirates,Asia,9890400.0,77.97,1.20,67293.483
105,Kuwait,Asia,4270563.0,75.49,2.00,65530.537
143,Norway,Europe,5421242.0,82.40,3.60,64800.057
183,Switzerland,Europe,8654618.0,83.78,4.53,57410.166
162,San Marino,Europe,33938.0,84.97,3.80,56861.470

In [174]:
df3 = df[df['population']>100000000]
df3

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
15,Bangladesh,Asia,1.646894e+08,72.59,0.80,3523.984
27,Brazil,South America,2.125594e+08,75.88,2.20,14103.452
41,China,Asia,1.439324e+09,76.91,4.34,15308.712
58,Egypt,Africa,1.023344e+08,71.99,1.60,10550.206
63,Ethiopia,Africa,1.149636e+08,66.60,0.30,1729.927
90,India,Asia,1.380004e+09,69.66,0.53,6426.674
91,Indonesia,Asia,2.735236e+08,71.72,1.04,11188.744
99,Japan,Asia,1.264765e+08,84.63,13.05,39002.223
125,Mexico,North America,1.289328e+08,75.05,1.38,17336.469
141,Nigeria,Africa,2.061396e+08,54.69,NaN,5338.454
145,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708
151,Philippines,Asia,1.095811e+08,71.23,1.00,7599.188
157,Russia,Europe,1.459345e+08,72.58,8.05,24765.954
199,United States,North America,3.310026e+08,78.86,2.77,54225.446

#3.4. Report the the number countries in each continent as a dataframe

In [186]:
continent = pd.Series(df['continent'])
continent_counts = continent.value_counts()
df4 = continent_counts.reset_index()
df4.columns = ['continent', 'number_of_countries']
df4

       continent  number_of_countries
0         Africa                   55
1         Europe                   51
2           Asia                   47
3  North America                   36
4  South America                   13
5        Oceania                    8

#3.5. Report the total population of each continent

In [192]:
continent = pd.Series(df['continent'])
df5 = df.groupby('continent')['population'].sum().reset_index()
df5.columns = ['continent', 'total_population']
df5

       continent  total_population
0         Africa      1.339424e+09
1           Asia      4.607388e+09
2         Europe      7.485062e+08
3  North America      5.912425e+08
4        Oceania      4.095832e+07
5  South America      4.304611e+08